# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET


on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ] # Listen for tag pushes that match version tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          
    - name: Restore dependencies
      run: |
        cd src
        cd OpenAPISwaggerUI
        dotnet restore
        dotnet tool restore
    - name: Build
      run: |
        cd src
        cd OpenAPISwaggerUI
        dotnet r pack
    - name: 'Upload nuget'
      uses: actions/upload-artifact@v4
      with:
        name: OpenApiSwagger_Nuget_${{github.run_number}}
        path: src/OpenAPISwaggerUI/output
        retention-days: 1

    - name: push to nuget
      if: startsWith(github.ref, 'refs/tags/v') # This line ensures the step runs only if a tag version is present
      run: |
        dir src/OpenAPISwaggerUI/output/*.*
        echo '1'
        dir src/OpenAPISwaggerUI/output/*.symbols.nupkg  
        echo '2'
        cd src
        cd OpenAPISwaggerUI
        cd output
        dotnet nuget push "*.symbols.nupkg" --api-key  ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        
  
    
